# Generated by Django 2.0.7 on 2018-09-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Perks of being a Wallflower', 'Perks of being a Wallflower'), ('All the bright places', 'All the bright places'), ('The Girl on the train', 'The Girl on the train'), ('Django', 'Django')], max_length=100)),
            ],
        ),
    ]
