# Generated by Django 2.0.7 on 2018-09-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(choices=[('Perks of being a Wallflower', 'Wallflower'), ('All the bright places', 'All the bright places'), ('The Girl on the train', 'The Girl on the train'), ('Django', 'Django')], max_length=100),
        ),
    ]
