# Generated by Django 2.0.7 on 2018-09-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180910_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(choices=[('All the bright places', 'All the bright places'), ('The Girl on the train', 'The Girl on the train'), ('Django', 'Django')], max_length=100),
        ),
    ]
