# Generated by Django 2.0.7 on 2018-09-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180910_0105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
